[rules."Disallow Unwrap"]
name = "Disallow Unwrap"
description = "`.unwrap()` should be discouraged where possible, as it leads to less than usefull panics."
help = "Use `.expect()`, `?` or `match` instead."
fail = false
range = [0, 3]
pattern = [["Punct", "."], ["Ident", "unwrap"], ["Delim", "("], ["Delim", ")"]]
replace = ".expect(\"...\")"